"""
Revision ID: 420c650723d1
Revises: 4fb3618a1f7a
Create Date: 2026-02-26 00:40:20.762522
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '420c650723d1'
down_revision: Union[str, None] = '4fb3618a1f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_teams_abbreviation', 'teams', ['abbreviation'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_teams_abbreviation', 'teams', type_='unique')
    # ### end Alembic commands ###
